function SWC(SWC_slow,SWC_fast,SWC_shock_candidate,SWC_CIR,colSlow,colFast,colCIR,colShock)
xregion(find(diff([false; SWC_slow])==1),find(diff([SWC_slow;false])==-1),'FaceColor',colSlow, ...
               'EdgeColor','none'); %Light blue
xregion(find(diff([false; SWC_fast])==1),find(diff([SWC_fast;false])==-1),'FaceColor',colFast, ...
               'EdgeColor','none'); %Light yellow
% xregion(find(diff([false; SWC_compression])==1),find(diff([SWC_compression;false])==-1),'FaceColor',[1.00 0.55 0.20], ...
%                'EdgeColor','none'); % Orange-red
xregion(find(diff([false; SWC_CIR])==1),find(diff([SWC_CIR;false])==-1),'FaceColor',colCIR, ...
               'EdgeColor','none'); % Orange-red
% xregion(find(diff([false; SWC_rarefaction])==1),find(diff([SWC_rarefaction;false])==-1),'FaceColor',[0.55 0.65 1.00], ...
%                'EdgeColor','none'); %Purple
xregion(find(diff([false; SWC_shock_candidate])==1),find(diff([SWC_shock_candidate;false])==-1),'FaceColor',colShock, ...
               'EdgeColor',colShock,'LineWidth',1,'FaceAlpha',0.25); %muted red
end
