function SWC(SWC_slow,SWC_fast,SWC_shock_candidate,SWC_CIR)
xregion(find(diff([false; SWC_slow])==1),find(diff([SWC_slow;false])==-1),'FaceColor',[0.75 0.85 1.00], ...
               'EdgeColor','none'); %Light blue
xregion(find(diff([false; SWC_fast])==1),find(diff([SWC_fast;false])==-1),'FaceColor',[1.00 0.95 0.65], ...
               'EdgeColor','none'); %Light yellow
% xregion(find(diff([false; SWC_compression])==1),find(diff([SWC_compression;false])==-1),'FaceColor',[1.00 0.55 0.20], ...
%                'EdgeColor','none'); % Orange-red
xregion(find(diff([false; SWC_CIR])==1),find(diff([SWC_CIR;false])==-1),'FaceColor',[1.00 0.55 0.20], ...
               'EdgeColor','none'); % Orange-red
% xregion(find(diff([false; SWC_rarefaction])==1),find(diff([SWC_rarefaction;false])==-1),'FaceColor',[0.55 0.65 1.00], ...
%                'EdgeColor','none'); %Purple
xregion(find(diff([false; SWC_shock_candidate])==1),find(diff([SWC_shock_candidate;false])==-1),'FaceColor',[0.90 0.45 0.45], ...
               'EdgeColor',[0.90 0.45 0.45],'LineWidth',1,'FaceAlpha',0.25); %muted red
end